/*
  Warnings:

  - You are about to drop the column `level` on the `teacher_subjects` table. All the data in the column will be lost.
  - A unique constraint covering the columns `[teacher_user_id,subject_id]` on the table `teacher_subjects` will be added. If there are existing duplicate values, this will fail.
  - Changed the type of `level` on the `bookings` table. No cast exists, the column would be dropped and recreated, which cannot be done if there is data, since the column is required.

*/
-- DropIndex
DROP INDEX "teacher_subjects_subject_id_level_idx";

-- DropIndex
DROP INDEX "teacher_subjects_teacher_user_id_subject_id_level_key";

-- MANUAL MIGRATION FOR "bookings" table 'level' column (enum to TEXT)
-- This replaces the problematic ALTER TABLE "bookings" statement generated by Prisma

-- Step 1: Add a new temporary column for 'level' (make it nullable initially)
ALTER TABLE "bookings" ADD COLUMN "level_new" TEXT;

-- Step 2: Copy data from the old 'level' enum column to the new 'level_new' text column
-- PostgreSQL can implicitly cast enum to text, but an explicit cast '::TEXT' is clearer
UPDATE "bookings" SET "level_new" = "level"::TEXT;

-- Step 3: Drop the old 'level' column
ALTER TABLE "bookings" DROP COLUMN "level";

-- Step 4: Rename the new column 'level_new' to 'level'
ALTER TABLE "bookings" RENAME COLUMN "level_new" TO "level";

-- Step 5: Add back the NOT NULL constraint
ALTER TABLE "bookings" ALTER COLUMN "level" SET NOT NULL;

-- END MANUAL MIGRATION


-- MANUAL ADJUSTMENT FOR "teacher_profiles" table 'specializations' column
-- Splitting ADD COLUMN and SET DEFAULT to potentially avoid shadow db syntax error

-- AlterTable (Add the column first)
ALTER TABLE "teacher_profiles" ADD COLUMN "specializations" TEXT[];

-- AlterTable (Now set the default)
ALTER TABLE "teacher_profiles" ALTER COLUMN "specializations" SET DEFAULT ARRAY[]::TEXT[];

-- END MANUAL ADJUSTMENT


-- AlterTable (These were also in the original generated file, keep them)
ALTER TABLE "teacher_subjects" DROP COLUMN "level",
ADD COLUMN "levels" TEXT[];

-- AlterTable (These were also in the original generated file, keep them)
ALTER TABLE "users" ADD COLUMN "languages" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "location" TEXT;

-- DropEnum (This must happen after columns using the enum are altered/dropped)
DROP TYPE "Level";

-- CreateIndex (These were also in the original generated file, keep them)
CREATE INDEX "teacher_subjects_subject_id_idx" ON "teacher_subjects"("subject_id");

-- CreateIndex (These were also in the original generated file, keep them)
CREATE UNIQUE INDEX "teacher_subjects_teacher_user_id_subject_id_key" ON "teacher_subjects"("teacher_user_id", "subject_id");